"""Add gravatar cache

Revision ID: 623ff94ea630
Revises: aeecea577c4c
Create Date: 2018-08-13 09:11:17.576469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623ff94ea630'
down_revision = 'aeecea577c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
